### ISSUE TITLE
"插件60秒未响应"

### ISSUE THREAD

**Issue by lixin4306ren** [yetone/bob-plugin-openai-polisher#10]
提示“插件60秒未响应”，不知道什么问题。
<img width="394" alt="image" src="https://user-images.githubusercontent.com/14223132/223601868-fee8a39d-8126-403e-bbe4-33734e43cfd1.png">

**Comment by lixin4306ren** [comment]
解决了，翻墙软件的问题，使用openai-polisher必须要翻墙。

**Comment by yaxiingz** [comment]
我的翻墙软件一直是挂着的还是有bug，是哪个代理网站要加入白名单吗？

**Comment by liby** [comment]
> 如果你们需要 ChatGPT/OPENAI 的代理规则（来源不记得了）：
> 
> # ChatGPT
> DOMAIN-SUFFIX,[http://openai.com](https://t.co/bFNscwS7jx),OPENAI // ChatGPT
> DOMAIN-SUFFIX,[http://openaiapi-site.azureedge.net](https://t.co/xXSR2SAEtl),OPENAI // ChatGPT
> DOMAIN-SUFFIX,[http://identrust.com](https://t.co/W3qWZuR2ul),OPENAI // ChatGPT
> DOMAIN-SUFFIX,[http://auth0.com](https://t.co/CIMvsbJXCS),OPENAI // ChatGPT

https://twitter.com/taresky/status/1641085318781874182?s=20
