### ISSUE TITLE
可否增加自定义prompt的功能

### ISSUE THREAD

**Issue by jinjunliu** [yetone/bob-plugin-openai-polisher#12]
首先感谢作者的插件，很好用。能否增加自定义润色prompt的功能？因为对于不同的润色目的，需要的着重点不同，比如科学写作，要求尽量严谨、不改变原意；而日常blog写作一般只要求语句通顺连贯即可。另外，自定义prompt也可以让用户微调，使结果更为灵活、可控。

**Comment by lixin4306ren** [comment]
是的，希望能给不同的prompt选择
