### ISSUE TITLE
 润色的时候能否支持自定义prompt，比如期望根据期刊不同风格进行润色

### ISSUE THREAD

**Issue by fredericky123** [yetone/bob-plugin-openai-polisher#22]
想借用这里的提示词：
https://ai.newzone.top/?tags=write
I want you to act as an professional spelling and grammer corrector and improver. I want you to replace my simplified A0-level words and sentences with more beautiful and elegant, upper level English words and sentences. Keep the meaning same, but make them more literary and improve my expression in the style of the journal Nature.

**Comment by fredericky123** [comment]
By the way:目前该版本的功能还是润色，能否增加个只检测语法而不润色的prompt

**Comment by liby** [comment]
[Custom prompt are supported
](https://github.com/yetone/bob-plugin-openai-polisher/releases/tag/v0.1.0)
