### ISSUE TITLE
想哭，怎么也用不了，显示“接口响应错误 - Invalid URL (POST /v1/chat/completions)”

### ISSUE THREAD

**Issue by Apeironzz** [yetone/bob-plugin-openai-polisher#9]
macbook M2 13.2.1的系统，下载的是最新的插件，fanqiang情况以及不fq，都显示“接口响应错误 - Invalid URL (POST /v1/chat/completions)”
以及，我这里open AI显示有一个API URL，这个没有改，但是我看教程上没有这一条。。

谢谢大神们！

![5551678182487_ pic](https://user-images.githubusercontent.com/113953882/223385652-60f07dbd-a982-40de-84a5-59b7a996c3ab.jpg)

![image](https://user-images.githubusercontent.com/113953882/223385762-3c9aaf11-5fd3-4a33-ad97-9b4706cbb2ac.png)

**Comment by RogerH2018** [comment]
我的显示
接口响应错误 - You exceeded your current quota, please check your plan and billing details.

**Comment by yetone** [comment]
@RogerH2018 related to https://github.com/yetone/openai-translator/issues/39#issuecomment-1457666269
